kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-java-wildfly
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: my-java-wildfly
          image: java-useless-image:latest
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
#          readinessProbe:
#            httpGet:
#              path: /health/ready
#              port: admin
#              scheme: HTTP
#            timeoutSeconds: 1
#            periodSeconds: 10
#            successThreshold: 1
#            failureThreshold: 3
#          terminationMessagePath: /dev/termination-log
#          livenessProbe:
#            httpGet:
#              path: /health/live
#              port: admin
#              scheme: HTTP
#            timeoutSeconds: 1
#            periodSeconds: 10
#            successThreshold: 1
#            failureThreshold: 3
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: admin
              containerPort: 9990
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: pipeline-devfile-example
spec:
ports:
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: 8080